<#
.SYNOPSIS
Creates a new Architecture Decision Record (ADR) with auto-numbering and cross-links.

.DESCRIPTION
ST-N-003: Generates ADR stubs under docs/adr/ with proper numbering (0007, 0008, etc.),
cross-links from plans, and consistent structure for module boundaries, gating rules,
or other architectural decisions.

.PARAMETER Title
Title of the decision (will be slugified for filename).

.PARAMETER Category
Category of decision: ModuleBoundary, GatingRule, Security, Performance, or Other.

.PARAMETER Context
Context/background for the decision (array of strings for bullet points).

.PARAMETER Decision
The decision being made (array of strings for bullet points).

.PARAMETER Consequences
Consequences of the decision (array of strings for bullet points).

.PARAMETER PlanReferences
Plan files to cross-link (e.g., PlanL, PlanN).

.PARAMETER TaskIds
Task IDs related to this decision (e.g., ST-L-001, ST-N-003).

.PARAMETER RepositoryRoot
Repository root path. Defaults to parent of script directory.

.PARAMETER PassThru
Return the ADR metadata as an object.
#>
param(
    [Parameter(Mandatory)][string]$Title,
    [ValidateSet('ModuleBoundary', 'GatingRule', 'Security', 'Performance', 'Other')]
    [string]$Category = 'Other',
    [string[]]$Context = @(),
    [string[]]$Decision = @(),
    [string[]]$Consequences = @(),
    [string[]]$PlanReferences = @(),
    [string[]]$TaskIds = @(),
    [string]$RepositoryRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path,
    [switch]$PassThru
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = (Resolve-Path -LiteralPath $RepositoryRoot).Path
$adrDir = Join-Path $repoRoot 'docs\adr'

if (-not (Test-Path -LiteralPath $adrDir)) {
    New-Item -ItemType Directory -Path $adrDir -Force | Out-Null
}

# Determine next ADR number
$existingAdrs = Get-ChildItem -LiteralPath $adrDir -Filter '*.md' -File -ErrorAction SilentlyContinue |
    Where-Object { $_.Name -match '^\d{4}-' }

$maxNumber = 0
foreach ($adr in $existingAdrs) {
    if ($adr.Name -match '^(\d{4})-') {
        $num = [int]$matches[1]
        if ($num -gt $maxNumber) { $maxNumber = $num }
    }
}

$nextNumber = $maxNumber + 1
$adrNumber = '{0:0000}' -f $nextNumber

# Slugify title
$slug = $Title.ToLowerInvariant() -replace '[^a-z0-9]+', '-' -replace '^-|-$', ''
$fileName = "{0}-{1}.md" -f $adrNumber, $slug
$filePath = Join-Path $adrDir $fileName

Write-Host ("Creating ADR {0}: {1}" -f $adrNumber, $Title) -ForegroundColor Cyan

# Build context section
$contextSection = if ($Context.Count -gt 0) {
    ($Context | ForEach-Object { "- $_" }) -join "`n"
} else {
    "- (Context to be added)"
}

# Build decision section
$decisionSection = if ($Decision.Count -gt 0) {
    ($Decision | ForEach-Object { "- $_" }) -join "`n"
} else {
    "- (Decision to be documented)"
}

# Build consequences section
$consequencesSection = if ($Consequences.Count -gt 0) {
    ($Consequences | ForEach-Object { "- $_" }) -join "`n"
} else {
    "- (Consequences to be evaluated)"
}

# Build references section
$referencesLines = [System.Collections.Generic.List[string]]::new()

if ($PlanReferences.Count -gt 0) {
    foreach ($plan in $PlanReferences) {
        $planPath = "../plans/{0}.md" -f $plan
        $referencesLines.Add("- [$plan]($planPath)")
    }
}

if ($TaskIds.Count -gt 0) {
    $referencesLines.Add("- Task Board IDs: $($TaskIds -join ', ')")
}

$referencesSection = if ($referencesLines.Count -gt 0) {
    $referencesLines -join "`n"
} else {
    "- (Add plan and task references)"
}

# Generate ADR content
$content = @"
# ADR $adrNumber - $Title

**Category:** $Category
**Date:** $(Get-Date -Format 'yyyy-MM-dd')
**Status:** Proposed

## Context
$contextSection

## Decision
$decisionSection

## Consequences
$consequencesSection

## References
$referencesSection

## Next Steps
- (Define implementation steps)
- (Update related plans/task board entries)

---
*Generated by Tools/New-ArchitectureDecisionRecord.ps1 (ST-N-003)*
"@

Set-Content -LiteralPath $filePath -Value $content -Encoding UTF8
Write-Host ("ADR written to: {0}" -f $filePath) -ForegroundColor Green

# Update plan files with cross-link if specified
foreach ($plan in $PlanReferences) {
    $planPath = Join-Path $repoRoot "docs\plans\${plan}.md"
    if (Test-Path -LiteralPath $planPath) {
        $planContent = Get-Content -LiteralPath $planPath -Raw
        $adrLink = "- [ADR ${adrNumber}: ${Title}](../adr/${fileName})"

        if ($planContent -notmatch [regex]::Escape($fileName)) {
            # Check if there's a References section
            if ($planContent -match '(?m)^## References') {
                # Insert after References header
                $planContent = $planContent -replace '(## References\r?\n)', "`$1$adrLink`n"
                Set-Content -LiteralPath $planPath -Value $planContent -Encoding UTF8
                Write-Host ("  Cross-linked from {0}" -f $plan) -ForegroundColor Green
            }
        }
    }
}

$result = [pscustomobject]@{
    Number         = $adrNumber
    Title          = $Title
    Category       = $Category
    FileName       = $fileName
    FilePath       = $filePath
    PlanReferences = $PlanReferences
    TaskIds        = $TaskIds
    Created        = Get-Date -Format 'o'
}

if ($PassThru) {
    return $result
}
