[CmdletBinding()]
param(
    # ST-N-002: Session log stub generation parameters
    [string]$Role = 'Automation',

    [string[]]$TaskIds,

    [string[]]$PlanReferences,

    [string[]]$Commands,

    [string[]]$ArtifactPaths,

    [string]$Notes,

    [string]$OutputPath,

    [switch]$PassThru
)

<#
.SYNOPSIS
Generates a session log stub for automation runs.

.DESCRIPTION
ST-N-002: Creates a pre-filled session log under docs/agents/sessions/ with commands,
artifact paths, and plan/task references. Designed to be called from harness scripts
like Invoke-StateTracePipeline and Invoke-WarmRunTelemetry.

.PARAMETER Role
Role category: Ingestion, Data, Automation, Docs, UI, or PMO. Defaults to Automation.

.PARAMETER TaskIds
Array of task IDs being worked on (e.g., ST-B-001, ST-E-002).

.PARAMETER PlanReferences
Array of plan references (e.g., PlanB, PlanE).

.PARAMETER Commands
Array of commands that were executed.

.PARAMETER ArtifactPaths
Array of artifact paths generated during the run.

.PARAMETER Notes
Additional notes or context for the session.

.PARAMETER OutputPath
Optional explicit output path. If not specified, generates a timestamped path under
docs/agents/sessions/.

.PARAMETER PassThru
Return the session log content as an object instead of just writing the file.

.EXAMPLE
pwsh Tools\New-SessionLogStub.ps1 -Role Automation -TaskIds ST-B-001 -Commands 'Invoke-StateTracePipeline' -ArtifactPaths 'Logs/IngestionMetrics/2026-01-04.json'

.EXAMPLE
$stub = pwsh Tools\New-SessionLogStub.ps1 -Role Ingestion -TaskIds ST-E-001,ST-E-002 -PassThru
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repositoryRoot = Split-Path -Parent $PSScriptRoot
$sessionsDir = Join-Path -Path $repositoryRoot -ChildPath 'docs\agents\sessions'
$timestamp = Get-Date -Format 'yyyy-MM-dd'
$timeDetail = Get-Date -Format 'HH:mm:ss'

# Generate session number for today
function Get-NextSessionNumber {
    param([string]$Directory, [string]$DatePrefix)

    if (-not (Test-Path -LiteralPath $Directory)) {
        return 1
    }

    $existing = Get-ChildItem -LiteralPath $Directory -Filter "${DatePrefix}_session-*.md" -File
    if (-not $existing -or $existing.Count -eq 0) {
        return 1
    }

    $maxNumber = 0
    foreach ($file in $existing) {
        if ($file.Name -match '_session-(\d+)\.md$') {
            $num = [int]$matches[1]
            if ($num -gt $maxNumber) {
                $maxNumber = $num
            }
        }
    }

    return $maxNumber + 1
}

# Determine output path
if (-not $OutputPath) {
    if (-not (Test-Path -LiteralPath $sessionsDir)) {
        New-Item -ItemType Directory -Path $sessionsDir -Force | Out-Null
    }
    $sessionNum = Get-NextSessionNumber -Directory $sessionsDir -DatePrefix $timestamp
    $sessionId = '{0:D4}' -f $sessionNum
    $OutputPath = Join-Path -Path $sessionsDir -ChildPath "${timestamp}_session-${sessionId}.md"
}

# Build task board card reference
$taskBoardCard = if ($TaskIds -and $TaskIds.Count -gt 0) {
    ($TaskIds | ForEach-Object { "- $_" }) -join "`n"
} else {
    '- (automated run)'
}

# Build plan bullets
$planBullets = if ($PlanReferences -and $PlanReferences.Count -gt 0) {
    ($PlanReferences | ForEach-Object { "- References: docs/plans/${_}.md" }) -join "`n"
} else {
    '- Automated harness run'
}

# Build commands section
$commandLines = if ($Commands -and $Commands.Count -gt 0) {
    "Commands executed:`n" + (($Commands | ForEach-Object { "  - ``$_``" }) -join "`n")
} else {
    'Commands executed: (harness invocation)'
}

# Build artifacts section
$artifactLines = if ($ArtifactPaths -and $ArtifactPaths.Count -gt 0) {
    ($ArtifactPaths | ForEach-Object { "  - $_" }) -join "`n"
} else {
    '  - (none captured)'
}

# Build notes section
$notesSection = if ($Notes) {
    "`n## Notes`n$Notes`n"
} else {
    ''
}

# Generate session log content
$content = @"
# Agent Session Log

- **Date:** $timestamp
- **Time:** $timeDetail
- **Role:** $Role
- **Task board card:**
$taskBoardCard

## Plan (automated)
$planBullets
- Harness-generated session stub (ST-N-002)

## Changes
- Files touched:
$artifactLines
- Rationale:
  - Automated run captured by harness script
$commandLines

## Validation
- Harness telemetry: See artifact paths above
- Tests: Run as part of harness execution
$notesSection
## Outcome
- Status: Pending review
- Follow-ups: Review generated artifacts and update task board

---
*This session log was auto-generated by Tools/New-SessionLogStub.ps1 (ST-N-002)*
"@

# Write output
$outputDir = Split-Path -Path $OutputPath -Parent
if ($outputDir -and -not (Test-Path -LiteralPath $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
}

Set-Content -LiteralPath $OutputPath -Value $content -Encoding utf8
Write-Host ("Session log stub written to: {0}" -f $OutputPath) -ForegroundColor DarkCyan

if ($PassThru) {
    return [pscustomobject]@{
        OutputPath = $OutputPath
        Date = $timestamp
        Time = $timeDetail
        Role = $Role
        TaskIds = $TaskIds
        PlanReferences = $PlanReferences
        Commands = $Commands
        ArtifactPaths = $ArtifactPaths
    }
}
