[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string[]]$QueueSummaryPaths,

    [string]$HistoryPath = (Join-Path -Path (Split-Path -Parent $PSScriptRoot) -ChildPath 'Logs\Reports\QueueDelayHistory.csv'),

    [int]$MinimumSampleCount = 10,

    [switch]$Force
)

<#
.SYNOPSIS
Appends queue-delay summary metadata to the historical CSV.

.DESCRIPTION
Reads one or more `QueueDelaySummary-*.json` files (generated by
`Tools\Generate-QueueDelaySummary.ps1` / `Tools\Invoke-StateTraceVerification.ps1`)
and appends their statistics to `Logs\Reports\QueueDelayHistory.csv`. Duplicate
entries (matching `SourceTelemetryPath`) are skipped unless `-Force` is passed.
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

if ($MinimumSampleCount -lt 1) { $MinimumSampleCount = 1 }

if (-not $QueueSummaryPaths -or $QueueSummaryPaths.Count -eq 0) {
    throw 'Specify at least one queue summary JSON path.'
}

$resolvedHistoryPath = [System.IO.Path]::GetFullPath($HistoryPath)
$historyDirectory = Split-Path -Parent $resolvedHistoryPath
if (-not (Test-Path -LiteralPath $historyDirectory)) {
    New-Item -Path $historyDirectory -ItemType Directory -Force | Out-Null
}

$existingSources = New-Object 'System.Collections.Generic.HashSet[string]' ([System.StringComparer]::OrdinalIgnoreCase)
if (Test-Path -LiteralPath $resolvedHistoryPath) {
    try {
        foreach ($row in (Import-Csv -LiteralPath $resolvedHistoryPath)) {
            if ($row.SourceTelemetryPath) {
                [void]$existingSources.Add($row.SourceTelemetryPath)
            }
        }
    } catch {
        Write-Warning ("Failed to read existing queue delay history at '{0}': {1}" -f $resolvedHistoryPath, $_.Exception.Message)
    }
}

$recordsToAppend = New-Object System.Collections.Generic.List[psobject]

foreach ($summaryPath in $QueueSummaryPaths) {
    if ([string]::IsNullOrWhiteSpace($summaryPath)) { continue }
    if (-not (Test-Path -LiteralPath $summaryPath)) {
        Write-Warning ("Queue summary '{0}' was not found; skipping." -f $summaryPath)
        continue
    }

    $summary = $null
    try {
        $content = Get-Content -LiteralPath $summaryPath -Raw
        $summary = $content | ConvertFrom-Json -ErrorAction Stop
    } catch {
        Write-Warning ("Failed to parse queue summary '{0}': {1}" -f $summaryPath, $_.Exception.Message)
        continue
    }

    $source = ''
    if ($summary.PSObject.Properties.Name -contains 'SourceTelemetryPath') {
        try { $source = (Resolve-Path -LiteralPath $summary.SourceTelemetryPath -ErrorAction Stop).Path } catch { $source = '' + $summary.SourceTelemetryPath }
    }

    if (-not $Force -and -not [string]::IsNullOrWhiteSpace($source) -and $existingSources.Contains($source)) {
        Write-Verbose ("Queue summary '{0}' (source '{1}') already recorded; skipping." -f $summaryPath, $source)
        continue
    }

    $delayStats = $null
    if ($summary.PSObject.Properties.Name -contains 'Statistics' -and $summary.Statistics.PSObject.Properties.Name -contains 'QueueBuildDelayMs') {
        $delayStats = $summary.Statistics.QueueBuildDelayMs
    }

    if (-not $delayStats) {
        Write-Warning ("Queue summary '{0}' does not contain QueueBuildDelayMs statistics; skipping." -f $summaryPath)
        continue
    }

    $sampleCountValue = Get-SampleCount -Stats $delayStats -FallbackContainer $summary
    if ($sampleCountValue -lt $MinimumSampleCount) {
        # LANDMARK: Queue delay sample floor - skip low-sample rollups
        Write-Warning ("Queue summary '{0}' reports {1} sample(s), below minimum {2}; skipping history append." -f $summaryPath, $sampleCountValue, $MinimumSampleCount)
        continue
    }

    $record = [pscustomobject]@{
        GeneratedAtUtc        = '' + $summary.GeneratedAtUtc
        SourceTelemetryPath   = $source
        SummaryPath           = (Resolve-Path -LiteralPath $summaryPath).Path
        SampleCount           = $sampleCountValue
        AverageQueueDelayMs   = [double]$delayStats.Average
        QueueDelayP95Ms       = [double]$delayStats.P95
        QueueDelayP99Ms       = [double]$delayStats.P99
        Pass                  = [bool]$summary.Pass
    }
    $recordsToAppend.Add($record) | Out-Null
    if (-not [string]::IsNullOrWhiteSpace($source)) {
        [void]$existingSources.Add($source)
    }
}

if ($recordsToAppend.Count -eq 0) {
    Write-Verbose 'No queue summary entries were appended.'
    return
}

$csvParameters = @{
    LiteralPath = $resolvedHistoryPath
    NoTypeInformation = $true
}
if (Test-Path -LiteralPath $resolvedHistoryPath) {
    $csvParameters['Append'] = $true
}

$recordsToAppend | Export-Csv @csvParameters
Write-Host ("Appended {0} queue delay entr{1} to {2}" -f $recordsToAppend.Count, $(if ($recordsToAppend.Count -eq 1) { 'y' } else { 'ies' }), $resolvedHistoryPath) -ForegroundColor Green

if ($PSCmdlet.ParameterSetName -eq '' -and $recordsToAppend.Count -gt 0) {
    return $recordsToAppend
}
